Fix layout and scrolling issues when going to landscape interface orientation
pitiphong-p/CollectionViewShelfLayout pull request #4
Opened 2017-03-31 12:59 UTC by damienrambout

I've noticed 2 bugs when using this layout in landscape orientation : 
1. The section header/footer bounds are not updated (i.e. they keep their original frame)
    + This has been fixed by overriding `shouldInvalidateLayout`.
2. The panning scrollviews are broken (you must scroll up/down to actually scroll left/right)
    + This has been fixed by adding/removing scrollviews to the collection view. The scrollviews are hidden (alpha = 0). This makes sure scrollviews work in any interface orientation.

2017-04-01 05:03 UTC, pitiphong-p commented
Thank you for this PR. I have some opinion on this.
1. The behavior that section headers/footers are not pinned to top is an intended behavior. If you want to include this feature into CollectionViewShelfLayout, I suggest you to add this as an opt-in feature with a mutable property
2. I believe this is a UIKit bug. I've investigated this for a moment and will update to you again later

2017-04-01 09:48 UTC, damienrambout commented
1. Headers and footers are not pinned. Their width is now updated when the bounds of collection view are updated. Otherwise, they were keeping their original width (i.e. Porta it's width)
2. I don't think this is a bug in UIKit. Views are meant to be added to a view hierarchy at some point. I believe `UIScrollView` can adapt its scrolling behavior thanks to its ancestor window.

2017-04-07 14:40 UTC, pitiphong-p commented
I did some recall by watching this [session](https://developer.apple.com/videos/play/wwdc2012/223/) again. I'm still a little bit confused but I can agree with you now that those `UIScrollView` need to be added to the view hierarchy.
By the way I still need you to change your code to match my convention and style.

2017-04-07 15:04 UTC, pitiphong-p requested changes

2017-04-07 15:04 UTC, pitiphong-p commented on CollectionViewShelfLayout/CollectionViewShelfLayout.swift
> +    return collectionView.frame.size != newBounds.size
Since we're supporting only the vertical layout. I think it would be better to compare just the width

2017-04-07 15:04 UTC, pitiphong-p commented on CollectionViewShelfLayout/CollectionViewShelfLayout.swift
> +      alpha = 0
I think we can move `alpha = 0` into its initializers and also set it `isHidden` property to false

2017-04-07 15:04 UTC, pitiphong-p commented on CollectionViewShelfLayout/CollectionViewShelfLayout.swift
> +        oldPanningScrollView.removeFromSuperview()
We should call `removeFromSuperview()` in the `willSet` `trackingView` property observer and also how's about calling `oldPanningScrollView.trackingView = nil` within a defer block after assigning the oldPanningScrollViews variable.

2017-04-07 15:04 UTC, pitiphong-p commented on CollectionViewShelfLayout/CollectionViewShelfLayout.swift
> +      alpha = 0
We don't need to set `translatesAutoresizingMaskIntoConstraints = false` here

2017-08-27 10:05 UTC, merged